=== dragorw/znackovaciJazyky/XML,XSD,XSL/Semestralni_prace.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="formulare">
    <xs:complexType>
      <xs:sequence>        
        <xs:element maxOccurs="unbounded" name="formular">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="jmeno" type="xs:string" />
              <xs:element name="prijmeni" type="xs:string" />
              <xs:element name="titul" type="xs:string" />
              <xs:element name="datum_narozeni" type="xs:string" />
              <xs:element name="rodne_cislo" type="xs:string" />
              <xs:element name="narodnost" type="xs:string" />
              <xs:element name="misto_narozeni" type="xs:string" />
              <xs:element name="misto_bydliste" type="xs:string" />              
              <xs:element name="PSC" type="xs:string" />
              <xs:element name="telefon" type="xs:string" />
              <xs:element name="e-mail" type="xs:string" />
              <xs:element name="webova_stranka" type="xs:string" />
              <xs:element name="ridicsky_prukaz" type="xs:string" />              
              <xs:element name="pocet_deti" type="xs:decimal" />
              <xs:element name="pocet_aut" type="xs:decimal" />
              <xs:element name="vzdelani" type="xs:string" />
              <xs:element name="zamestnani" type="xs:string" />
              <xs:element name="plat" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="cislo" type="xs:string" use="required" />
            <xs:attribute name="kod_registrace" type="xs:string" use="required" />
            <xs:attribute name="pohlavi" type="xs:string" use="required" />
            <xs:attribute name="invalidita" type="xs:string" use="required" />
            <xs:attribute name="vaha" type="xs:decimal" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dragorw/znackovaciJazyky/XML,XSD,XSL/Semestralni_prace.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Style.xsl"?>
<formulare 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Semestralni_prace.xsd"
>
    <formular cislo ="d1" kod_registrace="RK1" pohlavi ="muž" invalidita="ne" vaha="78">
            <jmeno>
                    Pavel
            </jmeno>            
            <prijmeni>
                    Novák
            </prijmeni>   
            <titul>
                    zadny
            </titul>            
            <datum_narozeni>
                    21.7.1991
            </datum_narozeni>            
            <rodne_cislo>
                    960525/0014
            </rodne_cislo>
            <narodnost>
                    Česká
            </narodnost>            
            <misto_narozeni>
                    Praha
            </misto_narozeni>            
            <misto_bydliste>
                    V úvaleh 1, Praha
            </misto_bydliste>
            <PSC>
                    158 00
            </PSC>
            <telefon>
                    7465468489    
            </telefon>
             <e-mail>
                     p.novak@seznam.cz
            </e-mail>
            <webova_stranka>
                        novak.cz
            </webova_stranka>
            <ridicsky_prukaz>
                        ODF454653
            </ridicsky_prukaz>
            <pocet_deti>
                    0
            </pocet_deti>  
            <pocet_aut>
                    1
            </pocet_aut> 
            <vzdelani>
                    Střední škola elektrotechnicka
            </vzdelani>
            <zamestnani>
                    elektrikař
            </zamestnani>            
            <plat>
                    32000
            </plat>

    </formular>

    <formular cislo="d2" kod_registrace="RK2" pohlavi ="muž" invalidita="ne" vaha="56">    
            <jmeno>
                    Tomáš
            </jmeno>            
            <prijmeni>
                    Klínský
            </prijmeni>            
            <titul>
                    Bc.
            </titul>            
            <datum_narozeni>
                    21.7.1995
            </datum_narozeni>            
            <rodne_cislo>
                    960525/0014
            </rodne_cislo>
            <narodnost>
                    Česká
            </narodnost>            
            <misto_narozeni>
                    Praha
            </misto_narozeni>            
            <misto_bydliste>
                    V úvaleh 1, Praha
            </misto_bydliste>
            <PSC>
                    158 00
            </PSC>
            <telefon>
                    7465468489    
            </telefon>
             <e-mail>
                     p.novak@seznam.cz
            </e-mail>
            <webova_stranka>
                        ------
            </webova_stranka>
            <ridicsky_prukaz>
                        ODEF475213
            </ridicsky_prukaz>
            <pocet_deti>
                    0
            </pocet_deti>            
            <pocet_aut>
                    1
            </pocet_aut>            
            <vzdelani>
                    Česká zemědělská univerzita
            </vzdelani>
            <zamestnani>
                    kovář
            </zamestnani>            
            <plat>
                    35000
            </plat>

    </formular>
         <formular cislo="d3" kod_registrace="RK3" pohlavi ="žena" invalidita="ne" vaha="67">
            <jmeno>
                    Veronika
            </jmeno>            
            <prijmeni>
                    Myslíková
            </prijmeni>
            <titul>
                    žádný
            </titul>
            <datum_narozeni>
                    15.02.1996
            </datum_narozeni>
            <rodne_cislo>
                    960215/0017
            </rodne_cislo>
            <narodnost>
                    Česká
            </narodnost>
            <misto_narozeni>
                    Brno
            </misto_narozeni>
            <misto_bydliste>
                    Strašniská 65, Praha
            </misto_bydliste>
            <PSC>
                    154 01
            </PSC>
            <telefon>
                    7548546589    
            </telefon>
             <e-mail>
                     veronika.m@seznam.cz
            </e-mail>
            <webova_stranka>
                        dVc.com
            </webova_stranka>
            <ridicsky_prukaz>
                        ODEF47544Ff
            </ridicsky_prukaz>
            <pocet_deti>
                    1
            </pocet_deti>
            <pocet_aut>
                    1
            </pocet_aut>
            <vzdelani>
                    Střední umělecká škola Václava Hollara
            </vzdelani>
            <zamestnani>
                    osvč
            </zamestnani>
            <plat>
                    -------
            </plat>
     </formular>
     
     <formular cislo="d4" kod_registrace="RK4" pohlavi ="muž" invalidita="ano" vaha="78">
            <jmeno>
                    Pavlo
            </jmeno>
            <prijmeni>
                    Mozart
            </prijmeni>
            <titul>
                    Ing
            </titul>
            <datum_narozeni>
                    29.11.1985
            </datum_narozeni>
            <rodne_cislo>
                    851129/095
            </rodne_cislo>
            <narodnost>
                    Německá
            </narodnost>
            <misto_narozeni>
                    Bern
            </misto_narozeni>
            <misto_bydliste>
                    Zeleznicka 15
            </misto_bydliste>
            <PSC>
                    188 20
            </PSC>
            <telefon>
                    545456489    
            </telefon>
             <e-mail>
                     p.mozart@adc.de
            </e-mail>
            <webova_stranka>
                        ------
            </webova_stranka>
            <ridicsky_prukaz>
                        5584F21F
            </ridicsky_prukaz>
            <pocet_deti>    
                    1
            </pocet_deti>
            <pocet_aut>
                    2
            </pocet_aut>
            <vzdelani>
                    Česká zemědělská univerzita
            </vzdelani>
            <zamestnani>
                    Zahradník
            </zamestnani>
            <plat>
                    25000
            </plat>
     </formular>

     <formular cislo="d5" kod_registrace="RK5" pohlavi ="muž" invalidita="ne" vaha="87">
            <jmeno>
                    Marek
            </jmeno>
            <prijmeni>
                    Urban
            </prijmeni>
            <titul>
                    žádný
            </titul>
            <datum_narozeni>
                    02.09.1991
            </datum_narozeni>
            <rodne_cislo>
                    960452/0058
            </rodne_cislo>
            <narodnost>
                    Česká
            </narodnost>
            <misto_narozeni>
                    Strakonice
            </misto_narozeni>
            <misto_bydliste>
                    V Úžlabině 15, Praha
            </misto_bydliste>
            <PSC>
                    147 02
            </PSC>
            <telefon>
                    775824565
            </telefon>
             <e-mail>
                     mara.urban@gmail.com
            </e-mail>
            <webova_stranka>
                        UrbanStrakonice.cz
            </webova_stranka>
            <ridicsky_prukaz>
                        ODEF475213
            </ridicsky_prukaz>
            <pocet_deti>
                    0
            </pocet_deti>
            <pocet_aut>
                    1
            </pocet_aut>
            <vzdelani>
                    Základní škola
            </vzdelani>
            <zamestnani>
                    Uklízeč
            </zamestnani>
            <plat>
                    17000
            </plat>
     </formular>

     <formular cislo="d6" kod_registrace="RK6" pohlavi ="muž" invalidita="ne" vaha="96">
            <jmeno>
                    Jaroslav
            </jmeno>
            <prijmeni>
                    Černý
            </prijmeni>
            <titul>
                    žádný
            </titul>
            <datum_narozeni>
                    17.03.1972
            </datum_narozeni>
            <rodne_cislo>
                    720317/0250
            </rodne_cislo>
            <narodnost>
                    Česká
            </narodnost>
            <misto_narozeni>
                    Praha
            </misto_narozeni>
            <misto_bydliste>
                    V úvalech 5
            </misto_bydliste>
            <PSC>
                    154 00
            </PSC>
            <telefon>
                    745484684    
            </telefon>
             <e-mail>
                     cerny.ja@seznam.cz
            </e-mail>
            <webova_stranka>
                        ------
            </webova_stranka>
            <ridicsky_prukaz>
                        O7452DEF47
            </ridicsky_prukaz>
            <pocet_deti>
                    2
            </pocet_deti>
            <pocet_aut>
                    2
            </pocet_aut>
            <vzdelani>
                    Střední odborné účeliště stavební
            </vzdelani>
            <zamestnani>
                    Řidič tramvaje
            </zamestnani>
            <plat>
                    28000
            </plat>
     </formular>

     <formular cislo="d7" kod_registrace="RK7" pohlavi ="žena" invalidita="ano" vaha="78">
            <jmeno>
                    Tereza
            </jmeno>
            <prijmeni>
                    Školníková
            </prijmeni>
            <titul>
